### ISSUE TITLE
Problem compiling under Archlinux

### ISSUE THREAD

**Issue by parzival3** [n-t-roff/DWB3.3#4]
I tried to compile in a Arch-Linux machine and the library inside the **index** folder cannot compile due to an error 

```
cc -O -s sbj1.o -o sbj1 
sbj1.o: In function `input':
sbj1.c:(.text+0x99a): undefined reference to `yywrap'
sbj1.o: In function `yylex':
sbj1.c:(.text+0x24e6): undefined reference to `yywrap'
collect2: error: ld returned 1 exit status
subj.mk:79: recipe for target 'sbj1' failed
make[2]: *** [sbj1] Error 1
rm sbj1.c
make[2]: Leaving directory '/home/enrico/Downloads/AUR/dwb-belllabs-git/src/dwb-belllabs-git/index/subj'
index.mk:57: recipe for target 'subj' failed
make[1]: *** [subj] Error 2
make[1]: Leaving directory '/home/enrico/Downloads/AUR/dwb-belllabs-git/src/dwb-belllabs-git/index'
dwb.mk:263: recipe for target 'index' failed
make: *** [index] Error 1
```

This can solve compiling those library with the **-lfl** flag

`cc -O -s sbj1.0 -o sbj1 -lfl`

**Comment by n-t-roff** [comment]
`./configure` should take care of it. What is written to `config.log`?

Please not that with ./confgiure `make -f dwb.mk` should not be used anymore. `-lfl` can't be written into the makefile since it doesn't work on e.g. solaris.

**Comment by n-t-roff** [comment]
Assumed to be solved
