### ISSUE TITLE
DWB4.1.3?

### ISSUE THREAD

**Issue by Alhadis** [n-t-roff/DWB3.3#7]
There appears to be a [newer release](https://archive.org/details/sgi_Documenters_Workbench_4.1.3) of Documenter's Workbench on Archive.org, seemingly newer than this one. Unfortunately, it's in some filesystem format I can't mount. The output of `file(1)` gives me this:

~~~console
λ ~/Downloads: file *.img
Documenter's Workbench 4.1.3.img: SGI disk label (volume header)
~~~

Any idea how this could be extracted?

**Comment by n-t-roff** [comment]
Thank you for this information!

When I type `fdisk -l Documenter\'s\ Workbench\ 4.1.3.img` on Linux I get
```
Disk Downloads/Documenter's Workbench 4.1.3.img: 23.3 MiB, 24440832 bytes, 47736 sectors
Geometry: 255 heads, 63 sectors/track, 2 cylinders
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: sgi

Device                             Start   End Sectors  Size Id Type       Attrs
Documenter's Workbench 4.1.3.img8     64 45335   45272 22.1M  5 SGI sysv        
Documenter's Workbench 4.1.3.img9      0    63      64   32K  0 SGI volhdr      
Documenter's Workbench 4.1.3.img11     0 45343   45344 22.1M  6 SGI volume      

Partition table entries are not in disk order.
```
So I assume when I `dd` this image to a disk, `/dev/sd`X`11` should be mountable, supposed it has directory version 2 (see https://lists.opensuse.org/opensuse/2005-11/msg04125.html, http://gllug.gllug.org.narkive.com/pBJgmk7o/mount-ancient-sgi-cds-on-current-ubuntu, or http://xfs.9218.n7.nabble.com/Mounting-IRIX-disk-on-Linux-td34218.html).

**Comment by Alhadis** [comment]
Getting it onto a disk is half the problem. Running `dd` gives me various errors on different systems.

**Fedora:**
> dd: failed to open '/dev/sr0': Read-only file system

**OpenBSD:**
> dd: /dev/rcd0c: Invalid argument
> 1+0 records in
> 0+0 records out
>
> dd: /dev/cd0c: end of device

And, of course, `mount` fails on both systems (as you'd expect):

> mount: wrong fs type, bad option, bad superblock on /dev/…

Regarding disks, I have only DVD+Rs on hand, and each of my available machines advise the use of `growisofs` or `wodim`. Both programs reportedly write ISO 9660 images —and I doubt they'd be able to burn an SGI filesystem to a DVD (although I've not attempted to do so myself).

> … supposed it has directory version 2

That's the other half of the problem. I've no way to determine which directory version it was ripped with. 😞

**Comment by Alhadis** [comment]
Interestingly enough, there're chunks of plain-text (shell-scripts) embedded inside the `img` file, which I discovered while poking through the raw binary data (I was out of options, heh).

~~~sh
#! /bin/sh
#Tag 0x00000600

# 'relnotes' - View on-line release notes; this version for online
# (on CD-ROM) release notes

# Use the code from the dirname shell script to save space
dirname()
{
ans=`/usr/bin/expr \
        "${1:-.}/" : '\(/\)/*[^/]*//*$' `
if [ -n "$ans" ];then
        echo $ans
else
        ans=`/usr/bin/expr \
                "${1:-.}/" : '\(.*[^/]\)//*[^/][^/]*//*$' `
        if [ -n "$ans" ];then
                echo $ans
        else
                echo "."
        fi
fi
exit 0
}

SRCDIR=`dirname $0`/relnotes/
~~~

I don't know if that's of any help in determining the disk's directory version, but it's an interesting observation (since the remainder of the disk is in binary).

**Comment by n-t-roff** [comment]
It may only work on an up-to-date Linux, because you need support for the XFS or even EFS file system. When you have it on a disk you shoud do a `fdisk -l sd`X to check the partition table and then try a `mount /dev/sd`X`11 /mnt` (if 11 is the SGI volume partition) to mount it.

You get the driectory version with the `xfs_db` command: Use `xfs_db /dev/sd`X`11`, then check the `versionnum` line. It must have a value >= 0x2000.

**Comment by Alhadis** [comment]
Goddamn it. It's a directory version 1. :disappointed:

~~~console
λ ~: xfs_db -F "Documenter's Workbench 4.1.3.img"
xfs_db: Documenter's Workbench 4.1.3.img is not a valid XFS filesystem (unexpected SB magic number 0x0be5a941)
xfs_db: V1 inodes unsupported. Please try an older xfsprogs.
~~~

That cinches it, then. I, erh, don't suppose you know anybody with an old IRIX machine? :grin:

I have `xfsprogs-4.15.1-1.fc28.x86_64` installed, so it can't be that `xfs_db` is outdated.

**Comment by Alhadis** [comment]
@n-t-roff I'm of the belief that the disc rip may actually be *corrupted*. I installed and ran @sophaskins' [`efs2tar`](https://github.com/sophaskins/efs2tar) utility and it generated a tarball which was impossibly small for a 25 MBs `.img` file:

~~~console
$ ~/go/bin/efs2tar -in DWB4.1.3.img -out DWB.tar

$ ls -alh
total 5712
drwxr-xr-x  2 Alhadis  wheel   512B Jul 16 10:43 .
drwx------  3 Alhadis  wheel   512B Jul 16 10:41 ..
-rwxr-xr-x  1 Alhadis  wheel   1.1M Jul 16 10:43 DWB.tar
-rw-r--r--  1 Alhadis  wheel  23.3M Jul 16 10:41 DWB4.1.3.img

$ bsdtar -xf DWB.tar
bsdtar: Removing leading '/' from member names

$ ls -alh
total 5752
drwxr-xr-x  4 Alhadis  wheel   512B Jul 16 10:43 .
drwx------  3 Alhadis  wheel   512B Jul 16 10:41 ..
-rwxr-xr-x  1 Alhadis  wheel   418B Jan  1  1970 CDgrelnotes
-rwxr-xr-x  1 Alhadis  wheel   3.6K Jan  1  1970 CDrelnotes
-rwxr-xr-x  1 Alhadis  wheel   1.1M Jul 16 10:43 DWB.tar
-rw-r--r--  1 Alhadis  wheel  23.3M Jul 16 10:41 DWB4.1.3.img
-rwxr-xr-x  1 Alhadis  wheel   126B Jan  1  1970 RELEASE.info
drwxr-xr-x  2 Alhadis  wheel   512B Jan  1  1970 dist
drwxr-xr-x  3 Alhadis  wheel   512B Jan  1  1970 relnotes
~~~

@sophaskins *did* mention that he'd only tested his tool lightly (and with one CD), but I've no knowledge of SGI's old filesystem format, so I have no way of telling where the cause of the tarball corruption might be...

**EDIT:** The "complete" contents of the botched tarball are listed below:
~~~console
$ bsdtar -tf DWB.tar
/CDgrelnotes
/CDrelnotes
/dist/dwb
/dist/dwb.idb
/dist/dwb.man
/dist/dwb.sw
/dist/.iscd
/dist
/relnotes/dwb/TC
/relnotes/dwb/ch1.z
/relnotes/dwb/ch2.z
/relnotes/dwb/ch3.z
/relnotes/dwb
/relnotes
/RELEASE.info
~~~
Which includes none of the plain-text directories that're visible and embedded inside the `.img` file. \*sigh\*...

**Comment by Alhadis** [comment]
Seems like `efs2tar` *did* extract the tarball correctly. Ripping the null bytes out of the `img` file produces a 1.1 MB file, roughly the same size as the (uncompressed) `.tar` file.

So it's clear the contents listed above are in fact the only files contained in the file. I'm just puzzled why somebody would upload such a thing when they had clear access to the CD.

**Comment by n-t-roff** [comment]
Ok. That's a pity. Thank you for investigating.

**Comment by nontroppo** [comment]
@Alhadis, this CD image _is_ complete. It contains files in the standard IRIX inst format.
IRIX inst reports the following:

```
Inst> from /CDROM/dist
Reading product descriptions ..  13% 
Reading /var/inst/hist
Reading product descriptions ..  25% 
Setting distribution to /CDROM/dist
Reading product descriptions .. 100% Done.

Inst> list
  View:      distribution
  Status:    N=new, U=upgrade, S=same, D=downgrade
  Stream:    maint
  Selection: i=install, r=remove, k=keep

  Subsystem Types [bdrpoc]:  b=reBoot needed, d=Default, r=Required, p=patch,
             o=overlay, c=Client only

i N  dwb.man.dwb [d]                  168+  Documenter's WorkBench online
                                            manual pages
i N  dwb.man.relnotes [d]              16+  Documenter's WorkBench online
                                            release notes
  N  dwb.sw.aps                        68+  Autologic APS-5 Fonts
i N  dwb.sw.dwb [d]                  2308+  Documenter's WorkBench
  N  dwb.sw.i10                       120+  Imagen Imprint-10 Fonts
i N  dwb.sw.share [d]                  52+  Documenter's WorkBench Shared Files

Disk space summary (Kbytes):            /

Current free space                 xxxxxx
- Selections net change              2552+
- Temporary inst overhead            2496+
= Minimum free during install      xxxxxx

Final projected free space         xxxxxx 
```

There is only ~1.1MB of non-null content  because that really is all it takes to contain this software distribution. `dist/dwb.idb` contains package file installation paths, permissions, checksums, &c.
The actual files are stored in compressed form in `dist/dwb.sw` and `dist/dwb.man`.

From relnotes/dwb/ch2.z:
>        2.5  Compatibility
> 
>        You must have IRIX 5.3 (or later) installed to run DWB
>        4.1.3.

**Comment by Alhadis** [comment]
So I'm taking it there's no source code? That really isn't much better....

**Comment by nontroppo** [comment]
I am afraid there is no source code contained in this CD image: only binary and platform-agnostic files.

**Comment by Alhadis** [comment]
That's a shame then, the source code for this release might vary well be lost to the sands of time.

Thanks for the enlightenment, though. :+1:

**Comment by Alhadis** [comment]
@nontroppo Just curious, how were you able to view these files? Do you have access to a working IRIX machine?

If so, are you able to extract the contents of the platform-agnostic files? Even if the binaries aren't runnable, the man-pages and readmes for this release could help shed light on what changed since DWB 3.3 and the (apparently?) final version, 4.1.3.
